inputs:
  APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD:
    required: true
  PP_PATH:
    required: true

runs:
  using: 'composite'

  steps:
    # https://docs.github.com/en/actions/guides/installing-an-apple-certificate-on-macos-runners-for-xcode-development
    - name: Install the Apple certificate and provisioning profile
      shell: bash
      env:
        P12_PASSWORD: ${{ inputs.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
        PP_PATH: ${{ inputs.PP_PATH }}
      run: |
        # create variables
        CERTIFICATE_PATH=secrets/AppleDistribution.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        KEYCHAIN_PASSWORD=$(openssl rand -base64 12)

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
