inputs:
  _APPENV_TS:
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo "$V" > shared/src/appenv.env.ts
      shell: bash
      env:
        V: ${{ inputs._APPENV_TS }}

    - run: npm install
      shell: bash
      working-directory: ./client

    - run: npm run build.cap
      shell: bash
      working-directory: ./client
