runs:
  using: 'composite'

  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    # https://github.com/actions/cache/blob/main/examples.md#java---gradle
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('capacitor/**/*.gradle*', 'capacitor/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
