export const ANNOUNCE_ID_LENGTH = 12;
export const ANNOUNCE_META_ID_LENGTH = 8;
export const POST_ID_LENGTH = 8;
export const NOTIFICATION_TOKEN_MAX_LENGTH = 300;
export const LANG_LENGTH = 2;

export const ANNOUNCE_META_NAME_MAX_LENGTH = 50;
export const ANNOUNCE_META_DESC_MAX_LENGTH = 500;
export const ANNOUNCE_META_LINK_MAX_LENGTH = 1000;

export const POST_TITLE_MAX_LENGTH = 100;
export const POST_BODY_MAX_LENGTH = 500;
export const POST_LINK_MAX_LENGTH = 1000;

export const IMAGE_ID_MAX_LENGTH = 25;
export const IMAGE_DATA_MAX_LENGTH = 1000 * 1000;

export const IMPORT_POSTS_URL_MAX_LENGTH = 1000;
export const IMPORT_POSTS_PUBKEY_MAX_LENGTH = 45;

export const REGISTER_NOTIFICATION_SIGNKEY_MAX_LENGTH = 45;
export const REGISTER_NOTIFICATION_SIGN_MAX_LENGTH = 90;
