/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Icons } from "../shared-web/components/ap-icon/ap-icon";
import { App } from "./app/app";
import { PageVisible } from "./shared";
export namespace Components {
    interface ApIcon {
        "icon"?: Icons;
    }
    interface AppAbout {
        "app": App;
    }
    interface AppAnnounce {
        "announceID": string;
        "app": App;
        "pageVisible": PageVisible;
    }
    interface AppAnnounceConfig {
        "announceID": string;
        "app": App;
        "pageVisible": PageVisible;
    }
    interface AppConfig {
        "app": App;
    }
    interface AppHome {
        "app": App;
        "pageVisible": PageVisible;
    }
    interface AppImage {
        "announceID": string;
        "app": App;
        "image62"?: string;
        "imageID"?: string;
        "postID": string;
    }
    interface AppPost {
        "announceID": string;
        "app": App;
        "pageVisible": PageVisible;
        "postID": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLApIconElement extends Components.ApIcon, HTMLStencilElement {
    }
    var HTMLApIconElement: {
        prototype: HTMLApIconElement;
        new (): HTMLApIconElement;
    };
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppAnnounceElement extends Components.AppAnnounce, HTMLStencilElement {
    }
    var HTMLAppAnnounceElement: {
        prototype: HTMLAppAnnounceElement;
        new (): HTMLAppAnnounceElement;
    };
    interface HTMLAppAnnounceConfigElement extends Components.AppAnnounceConfig, HTMLStencilElement {
    }
    var HTMLAppAnnounceConfigElement: {
        prototype: HTMLAppAnnounceConfigElement;
        new (): HTMLAppAnnounceConfigElement;
    };
    interface HTMLAppConfigElement extends Components.AppConfig, HTMLStencilElement {
    }
    var HTMLAppConfigElement: {
        prototype: HTMLAppConfigElement;
        new (): HTMLAppConfigElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImageElement extends Components.AppImage, HTMLStencilElement {
    }
    var HTMLAppImageElement: {
        prototype: HTMLAppImageElement;
        new (): HTMLAppImageElement;
    };
    interface HTMLAppPostElement extends Components.AppPost, HTMLStencilElement {
    }
    var HTMLAppPostElement: {
        prototype: HTMLAppPostElement;
        new (): HTMLAppPostElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "ap-icon": HTMLApIconElement;
        "app-about": HTMLAppAboutElement;
        "app-announce": HTMLAppAnnounceElement;
        "app-announce-config": HTMLAppAnnounceConfigElement;
        "app-config": HTMLAppConfigElement;
        "app-home": HTMLAppHomeElement;
        "app-image": HTMLAppImageElement;
        "app-post": HTMLAppPostElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface ApIcon {
        "icon"?: Icons;
    }
    interface AppAbout {
        "app": App;
    }
    interface AppAnnounce {
        "announceID": string;
        "app": App;
        "pageVisible": PageVisible;
    }
    interface AppAnnounceConfig {
        "announceID": string;
        "app": App;
        "pageVisible": PageVisible;
    }
    interface AppConfig {
        "app": App;
    }
    interface AppHome {
        "app": App;
        "pageVisible": PageVisible;
    }
    interface AppImage {
        "announceID": string;
        "app": App;
        "image62"?: string;
        "imageID"?: string;
        "postID": string;
    }
    interface AppPost {
        "announceID": string;
        "app": App;
        "pageVisible": PageVisible;
        "postID": string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "ap-icon": ApIcon;
        "app-about": AppAbout;
        "app-announce": AppAnnounce;
        "app-announce-config": AppAnnounceConfig;
        "app-config": AppConfig;
        "app-home": AppHome;
        "app-image": AppImage;
        "app-post": AppPost;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ap-icon": LocalJSX.ApIcon & JSXBase.HTMLAttributes<HTMLApIconElement>;
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-announce": LocalJSX.AppAnnounce & JSXBase.HTMLAttributes<HTMLAppAnnounceElement>;
            "app-announce-config": LocalJSX.AppAnnounceConfig & JSXBase.HTMLAttributes<HTMLAppAnnounceConfigElement>;
            "app-config": LocalJSX.AppConfig & JSXBase.HTMLAttributes<HTMLAppConfigElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-image": LocalJSX.AppImage & JSXBase.HTMLAttributes<HTMLAppImageElement>;
            "app-post": LocalJSX.AppPost & JSXBase.HTMLAttributes<HTMLAppPostElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
