name: build-client-ios-release

on: workflow_dispatch

jobs:
  build:
    runs-on: macOS-11

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/build-setup
        with:
          SECRET_VALUES: ${{ secrets.SECRET_VALUES }}
        id: build_setup

      - uses: ./.github/workflows/build-setup/ios

      - uses: ./.github/workflows/provisioning-profile-setup
        with:
          APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          PP_PATH: 'secrets/Release.mobileprovision'

      - run: npm run - client.cap.build
      - run: npm run - client.cap.sync

      - run: >-
          xcodebuild 
          CODE_SIGN_STYLE=Manual
          CODE_SIGN_IDENTITY="Apple Distribution"
          BUNDLE_DISPLAY_NAME=${BUNDLE_DISPLAY_NAME}
          PROVISIONING_PROFILE_SPECIFIER="${PP_SPECIFIER}"
          BUNDLE_IDENTIFIER="${BUNDLE_IDENTIFIER}"
          BUNDLE_VERSION="${BUNDLE_VERSION}"
          BUNDLE_VERSION_STRING="${BUNDLE_VERSION_STRING}"
          -quiet
          -workspace App.xcworkspace
          -scheme App
          -configuration Release
          -archivePath $RUNNER_TEMP/announcing.xcarchive 
          archive
          &&
          xcodebuild
          -quiet
          -exportArchive
          -archivePath $RUNNER_TEMP/announcing.xcarchive
          -exportPath $RUNNER_TEMP/announcing.ipa
          -exportOptionsPlist ../../ios-export-release.plist
        working-directory: ./capacitor/client/ios/App
        env:
          PP_SPECIFIER: 'announcing client Release'
          BUNDLE_IDENTIFIER: 'app.announcing.client'
          BUNDLE_DISPLAY_NAME: Announcing♪
          BUNDLE_VERSION: ${{ steps.build_setup.outputs.BUILD_NUMBER }}
          BUNDLE_VERSION_STRING: ${{ steps.build_setup.outputs.APP_VERSION }}

      - uses: actions/upload-artifact@v2
        with:
          name: announcing-release-${{ steps.build_setup.outputs.BUILD_NUMBER }}-${{ steps.build_setup.outputs.APP_VERSION }}.ipa
          path: ${{ runner.temp }}/announcing.ipa

      - run: mkdir private_keys

      - run: echo "${KEY}" > private_keys/AuthKey_${API_KEY}.p8
        env:
          KEY: ${{ secrets.APPSTORE_KEY }}
          API_KEY: ${{ steps.build_setup.outputs.APPSTORE_API_KEY }}

      - run: >-
          xcrun altool --upload-app -f $RUNNER_TEMP/announcing.ipa/App.ipa -t ios
          --apiKey ${API_KEY} --apiIssuer ${API_ISSUER}
        env:
          API_KEY: ${{ steps.build_setup.outputs.APPSTORE_API_KEY }}
          API_ISSUER: ${{ steps.build_setup.outputs.APPSTORE_API_ISSUER }}

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/Release.mobileprovision
